Test new pipeline with force fail

diff --git a/.github/workflows/check-and-test.yml b/.github/workflows/check-and-test.yml
--- a/.github/workflows/check-and-test.yml
+++ b/.github/workflows/check-and-test.yml
@@ -19,6 +19,11 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v5
 
+      - name: Force fail
+        run: |
+          echo "Force fail"
+          exit 1
+
       - name: Setup Node
         uses: actions/setup-node@v5
         with:
